### ISSUE TITLE
Replace to JSR package

### ISSUE THREAD

**Issue by windchime-yk** [rwl-dev/bid#34]
I planed all my deno.land/x module replace to JSR package!
Therefore, all settings change! However, there is no impact on users. The import source is simply changed to JSR.

## Tasks
- [x] Rename package(bid → Tsuduri)
- [x] organizing dependencies
  - [x] delete deps.ts
  - [x] delete deno.land/x module

**Comment by windchime-yk** [comment]
Oh, I publish to JSR yet.
I create publish Issue.
